# generated by datamodel-codegen:
#   filename:  acme_config.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union


@dataclass
class Meta:
    """
    JSON object of the content of meta.json
    """

    uri: Optional[str] = None


@dataclass
class Registration:
    """
    JSON object of the content of regr.json
    """

    uri: Optional[str] = None


@dataclass
class Account:
    account_id: str
    endpoint: str
    """
    ACME API endpoint the account is registered with
    """
    dirname: str
    """
    The hash of the directory to store the files into
    """
    created_on: Optional[str] = None
    """
    created_dt from meta.json
    """
    privateKey: Optional[Union[Dict[str, Any], str]] = None
    meta: Optional[Union[Meta, str]] = None
    registration: Optional[Union[Registration, str]] = None


@dataclass
class AcmeConfig:
    """
    acme secret configuration format
    """

    accounts: List[Account]
    store_arn: Optional[str] = None
